version: "3"

services:
  db:
    image: mysql:8.3
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=zapps_library
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: pma
    links:
      - db
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: admin
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata:
