"""fix cascade

Revision ID: 0658c6eabfea
Revises: cfb3cfe8c0bc
Create Date: 2024-01-24 09:29:38.600169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0658c6eabfea'
down_revision = 'cfb3cfe8c0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returned_book', schema=None) as batch_op:
        batch_op.drop_constraint('returned_book_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returned_book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('returned_book_ibfk_1', 'book', ['book_id'], ['id'])

    # ### end Alembic commands ###
