"""update borrow_book

Revision ID: 7022f3ea4171
Revises: 7c22720e6a45
Create Date: 2024-01-25 10:34:33.076397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7022f3ea4171'
down_revision = '7c22720e6a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lost', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_damaged', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('late_fee', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('additional_fee', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_book', schema=None) as batch_op:
        batch_op.drop_column('additional_fee')
        batch_op.drop_column('late_fee')
        batch_op.drop_column('is_damaged')
        batch_op.drop_column('is_lost')

    # ### end Alembic commands ###
