"""make borrow dates nullable

Revision ID: b44ac56ca9b3
Revises: fd0c0d65066d
Create Date: 2024-01-25 05:13:19.786951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b44ac56ca9b3'
down_revision = 'fd0c0d65066d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_book', schema=None) as batch_op:
        batch_op.alter_column('borrow_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('return_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_book', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('borrow_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
