"""add model ReturnedBook

Revision ID: cfb3cfe8c0bc
Revises: c666fefeee4a
Create Date: 2024-01-23 22:45:38.881135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb3cfe8c0bc'
down_revision = 'c666fefeee4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returned_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('late_fee', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('returned_book')
    # ### end Alembic commands ###
