"""change superuser to superadmin

Revision ID: dedd1526451b
Revises: 997b228c55ec
Create Date: 2024-01-23 21:44:09.487696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedd1526451b'
down_revision = '997b228c55ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('SUPERADMIN', 'ADMIN', 'MEMBER', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('SUPERADMIN', 'ADMIN', 'MEMBER', name='userrole'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
