"""fix cascade book user

Revision ID: fd0c0d65066d
Revises: 0658c6eabfea
Create Date: 2024-01-24 09:31:26.816633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0c0d65066d'
down_revision = '0658c6eabfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returned_book', schema=None) as batch_op:
        batch_op.drop_constraint('returned_book_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['member_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returned_book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('returned_book_ibfk_2', 'user', ['member_id'], ['id'])

    # ### end Alembic commands ###
